[phases.setup]
nixPkgs = [
  "python311",
  "glib",
  "gtk3",
  "nspr",
  "nss",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "mesa",
  "pango",
  "cairo",
  "alsa-lib",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libXtst",
  "xorg.libXScrnSaver",
  "libxkbcommon",
  "libgbm"
]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[start]
cmd = "python app.py"
